# This workflow will install Divio CLI and deploy into Divio on a push event
 
name: Divio Continuous Deployment
 
# push event to master branch triggers the workflow
on:
 push:
   branches: [ master ]
 
# jobs run sequentially or in parallel to execute the workflow
jobs:
 
 # This workflow contains a single job called "deploy"
 deploy:
  # Setting environment variables of the secret keys for easy access
   env:
     DIVIO_API_TOKEN: ${{ secrets.DIVIO_API_TOKEN }}
     TEST_ENVIRONMENT: ${{ secrets.TEST_ENVIRONMENT }}
     LIVE_ENVIRONMENT: ${{ secrets.LIVE_ENVIRONMENT }}
  
  # The type of runner that this job will run on
   runs-on: ubuntu-latest
 # Steps represent a sequence of tasks that will be executed as part of the job
   steps:
   # Checks-out the repository under $GITHUB_WORKSPACE, so this job can access it
   - uses: actions/checkout@v2
   
   - name: Deploy to Divio Cloud using the API
     run: |
  # To deploy to TEST    
       curl -X POST --data "environment=$TEST_ENVIRONMENT" --header "Authorization: Token $DIVIO_API_TOKEN" https://api.divio.com/apps/v3/deployments/
   # To deploy to LIVE     
       curl -X POST --data "environment=$LIVE_ENVIRONMENT" --header "Authorization: Token $DIVIO_API_TOKEN" https://api.divio.com/apps/v3/deployments/
  
